apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
    name: app1
spec:
  containers:
  - name: app1-container
    image: busybox
    command: ["/bin/sh", "-c", "env"]
    env:
    - name: SPECIAL_LEVEL_KEY
      valueFrom:
        configMapKeyRef:
          name: special-config
          key:  special.how
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Never
