apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis-container
    image:  redis
    volumeMounts:
    - name:  config
      mountPath:  /redis-master

  volumes:
    - name:  config
      configMap: 
        name: example-redis-config
        items:
        - key: redis.conf
          path: redis.conf