apiVersion: v1
kind: Pod
metadata:
  name: pod-secret
  labels:
    name: pod-secret
spec:
  containers:
  - name: pod-secret-container
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name:  mysecret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name:  mysecret
          key: password
  restartPolicy: Never